### ISSUE TITLE
Example of AES encryption

### ISSUE THREAD

**Issue by abhijeetkpawar** [bitwiseshiftleft/sjcl#237]
Any example of the AES encryption API would be useful

**Comment by Bren2010** [comment]
https://github.com/bitwiseshiftleft/sjcl/wiki/Directly-Using-Ciphers

**Comment by abhijeetkpawar** [comment]
Thanks. That gives a quick view, but would be nice if there is detailed example from key generation to encryption along with info of every bit.
One query - Is it possible to encrypt longer text in one go?

**Comment by Nilos** [comment]
Hey,
do you need plain aes for some legacy compatibility? Because usually using the sjcl.encrypt function is way easier and also a lot more secure.

Encrypting longer text in one go is not possible without a loop or by using a cipher mode (which you should use: https://en.wikipedia.org/wiki/Block_cipher_mode_of_operation#Electronic_Codebook_.28ECB.29)

Anyhow key generation can be done by using sjcl.random:
```
sjcl.random.randomWords(8);
```

**Comment by abhijeetkpawar** [comment]
I wanted to use AES, but the default will also do in my case. Thanks for the information.
