### ISSUE TITLE
Scrypt not in sjcl.js and thus not available when getting from Node

### ISSUE THREAD

**Issue by tasn** [bitwiseshiftleft/sjcl#348]
Hey,

As said in the title, the sjcl.js file is a bit outdated and doesn't include scrypt.js. Could you please regenerate that so it's available for people installing from node in the future?

Edit: it looks like just a regen doesn't include it, I guess something else is missing too, maybe it was not added to the build process?

Thanks,
Tom.

**Comment by elrido** [comment]
I was investigating why sjcl.codec.bytes was missing and found the dependencies in the [configure](https://github.com/bitwiseshiftleft/sjcl/blob/master/configure#L27) file. But it is missing in [config.mk](https://github.com/bitwiseshiftleft/sjcl/blob/master/config.mk). If I understand the build process correctly, for scrypt support both `core/scrypt.js` and `core/codecBytes.js` would need to be added to the `SOURCES`.

**Comment by luczsoma** [comment]
Could you guys look into this?

**Comment by Nilos** [comment]
Scrypt is not currently part of the bundle on npm. The idea was to keep sjcl as small as possible in the default configuration and with pbkdf2 there is already one key derivation function included.

**Comment by robyoder** [comment]
Hey, @Nilos. With the advent of ES modules, Rollup, etc. tree shaking or dead code elimination is easier than ever before. Would you consider a PR that builds all of sjcl as ES modules (using the `module` entry in package.json) so that folks can install from npm and let their bundlers do the work to minimize bundle size for dead code?
